spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wechat_bot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 
#    type: com.alibaba.druid.pool.DruidDataSource

    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

    tomcat:
      init-s-q-l: SET NAMES utf8mb4